[build]
  publish = "."
  command = ""

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  DISABLE_FRAMEWORK_DETECTION = "true"

[[redirects]]
  from = "/@vite/*"
  to = "/@vite/client"
  status = 200

[[redirects]]
  from = "/@id/*"
  to = "/404-not-found-static"
  status = 404

[[redirects]]
  from = "/*.js"
  to = "/404-not-found-static"
  status = 404

[[redirects]]
  from = "/*.css"
  to = "/404-not-found-static"
  status = 404

[[redirects]]
  from = "/*.map"
  to = "/404-not-found-static"
  status = 404

[[redirects]]
  from = "/*.ts"
  to = "/404-not-found-static"
  status = 404
  force = true

[[redirects]]
  from = "/*.tsx"
  to = "/404-not-found-static"
  status = 404
  force = true

[[redirects]]
  from = "/*.woff"
  to = "/404-not-found-static"
  status = 404

[[redirects]]
  from = "/*.woff2"
  to = "/404-not-found-static"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=86400; includeSubDomains"
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/@vite/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-store"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
